### PR TITLE
Move entries to rows and click and drag to sort rows

### PR DESCRIPTION
**Pull request by johndaskovsky**

### CODE REVIEW

**Comment by johndaskovsky** [comment]
Hey B, I'm excited about what I was able to get done with this! Add entries and then sort rows by click and drag. Still a bunch more to do:
- remove entries
- edit entries
- form validation
- improve true/false input

Hope to get this stuff done tomorrow night... we'll see =)

**Comment by johndaskovsky** [comment]
@cyhtan 
Looks like this didn't quite work. I added some dependancies to the lib folder and to a new folder: fonts. I think you might need to configure something in the server to get this folders to be read properly.

Thanks,
John

**Comment by cyhtan** [comment]
Cool, I'll look into it tomorrow. Thanks for heads up!

**Comment by cyhtan** [comment]
Hey, I fixed the jQuery UI reference, but when clicking the Save New Entry
button, console throws the error _"addEntry is not defined (onclick @
(index):55)."_

Is this the "addPIDEntry()" in SID.js? I tried changing in my local copy,
but it threw the same error, now: "addPIDEntry is not defined."

Was this not happening for you on your local copy?

Excited to figure out what's going on! Let me know if you have any ideas.
Otherwise we can just look into it Monday.

B

**Comment by johndaskovsky** [comment]
Yeah button still isn't working. Just press "enter" when adding entires.

**Comment by cyhtan** [comment]
Oh, okay. Thanks! 

(in other news, I think we'll be switching our collaboration remote repo to BitBucket for privacy reasons... we can talk on Monday about it though.)

**Pull request merged**
